### ISSUE TITLE
Discriminated union arms value

### ISSUE THREAD

**Issue by fracek** [kochavalabs/xdr-rs-serialize#17]
## Describe the feature 

I need to serialize/deserialize a discriminated union where the arms discriminant are not an increasing sequence:

```
enum FooType
{
   A = 1,
   B = 10,
   C = 100
};

union Foo (FooType code)
{
case A:
  void;
case B:
  void;
case C:
  void;
default:
  void;
};
```

In Rust I have the following types:

```rust

#[derive(PartialEq, Clone, Debug, XDROut, XDRIn)]
pub enum FooType {
    A = 1,
    B = 10,
    C = 100,
}


#[derive(PartialEq, Clone, Debug, XDROut, XDRIn)]
pub enum Foo {
    A(), // Discriminant: 1
    B(), // Discriminant: 10
    C(), // Discriminant: 100
    D(), // Discriminant: any
}
```

Is there a way already to specify the discriminant? If not, would you accept a PR to add an attribute for this?

```rust
#[derive(PartialEq, Clone, Debug, XDROut, XDRIn)]
pub enum Foo {
    #[discriminant(value = FooType::A)]
    A(), // Discriminant: 1
    #[discriminant(value = FooType::B)]
    B(), // Discriminant: 10
    #[discriminant(value = FooType::C)]
    C(), // Discriminant: 100
    // No attribute, consider as default and use 0?
    D(), // Discriminant: any
}
```

**Comment by kbartush** [comment]
Thanks for the feature request. I'm going to be working off the definition here: https://tools.ietf.org/html/rfc4506#section-4.15

Our implementation has a few short falls, what we have available for union types is fairly basic. We don't currently have a working default arm and make a few assumptions about the discriminant. This really feels like two separate features, the default arm and the ability to specify discriminants.

I am slightly concerned about allowing any type to be specified for the discriminant because they must be 4 bytes. Maybe consider requiring a specific discriminant using hex and piecing together what should be generated in xdr-codegen (if you're using that). 

We don't really use these features so this won't be a high priority for me to work on, but it's a good request and I would be happy to review pull requests.

**Comment by fracek** [comment]
I spent more time thinking about this, and I think the problem is that XDR unions are different enough from Rust discriminated unions that not all of their values can be represented in Rust. As an example, there is no obvious way (to me) to represent this union:

```xdr
union Foo (int code)
{
case 0:
    void;
default:
    void;
}
```

My use case is to generate [types for Stellar](https://github.com/stellar/stellar-core/tree/master/src/xdr), which luckily does not use this pattern. I need to generate this type of unions:

```xdr
    union switch (int v)
    {
    case 0:
        void;
    case 1:
        V1 v1;
    }
```

Which is already possible to represent:

```rust
#[derive(Debug, XDROut, XDRIn)]
pub enum SampleUnion {
    Void(()),
    V1(V1),
}
```

And this type:

```xdr
enum CreateAccountResultCode
{
    CREATE_ACCOUNT_SUCCESS = 0, // account was created
    CREATE_ACCOUNT_MALFORMED = -1,   // invalid destination
    // some more cases
};

union CreateAccountResult switch (CreateAccountResultCode code)
{
case CREATE_ACCOUNT_SUCCESS:
    Success success;
default:
    void;
};
```

In this case, the code generator will expand the default value to include all cases of the enum discriminant.

```rust
pub enum CreateAccountResultCode {
    Success = 0,
    Malformed = -1
}

pub enum CreateAccountResult {
    #[discriminant(value = CreateAccountResultCode::Success)]
    Success(Success),
    #[discriminant(value = CreateAccountResultCode::Malformed)]
    Malformed(()),
    // more cases like Malformed
}
```

With this consideration in mind, I think I only need to implement the discriminant attribute. Any thoughts?

**Comment by kbartush** [comment]
A few thoughts:

I would suggest that when you create these enums you use the actual case statement to form the enum member names. For example what happens if there are two voids in your first example:

```xdr
    union switch (int v)
    {
    case 0:
        void;
    case 1:
        V1 v1;
    case 2:
        void;
    }
```

So instead I would suggest you form enums more like this (if you want pretty names use an enum not an int code):

```rust
#[derive(Debug, XDROut, XDRIn)]
pub enum SampleUnion {
    C0(()),
    C1(V1),
    C2(()),
}
```

As for the default feature, the XDROut macro expands to something like this:
```rust
impl XDROut for SampleUnion {
    fn write_xdr(&self, out: &mut Vec<u8>) -> Result<u64, Error> {
        match *self {
            SampleUnion::Void(ref val) => {
                let mut written = 0;
                written += 0.write_xdr(out)?;
                written += val.write_xdr(out)?;
                Ok(written)
            }
            SampleUnion::V1(ref val) => {
                let mut written = 0;
                written += 1.write_xdr(out)?;
                written += val.write_xdr(out)?;
                Ok(written)
            }
            _ => Err(Error::InvalidEnumValue),
        }
    }
    fn write_json(&self, out: &mut Vec<u8>) -> Result<u64, Error> {
        match *self {
            SampleUnion::Void(ref val) => {
                let mut written = 0;
                written += out.write("{\"enum\":".as_bytes()).unwrap() as u64;
                written += 0.write_json(out)?;
                written += out.write(",\"value\":".as_bytes()).unwrap() as u64;
                written += val.write_json(out)?;
                written += out.write("}".as_bytes()).unwrap() as u64;
                Ok(written)
            }
            SampleUnion::V1(ref val) => {
                let mut written = 0;
                written += out.write("{\"enum\":".as_bytes()).unwrap() as u64;
                written += 1.write_json(out)?;
                written += out.write(",\"value\":".as_bytes()).unwrap() as u64;
                written += val.write_json(out)?;
                written += out.write("}".as_bytes()).unwrap() as u64;
                Ok(written)
            }
            _ => Err(Error::InvalidEnumValue),
        }
    }
}
```

This was the first rust macro I ever wrote, so it's pretty ugly. But generally I think you could just update the fall though case of the match to be what you want for the default arm inside the macro. I think the issue with enumerating each case is that the default arm should be hit for cases that don't exist in the enum (If you want to enumerate each case just do that inside your xdr union.) For example the xdr binary 0x00000003 should be a valid CreateAccountResult based on the union definition.

I have tried to avoid default, we chose XDR so that there wasn't ambiguity in our data types that may cause trouble when signing our objects across languages and implementations. It doesn't look like this really matters for CreateAccountResult though.

**Comment by fracek** [comment]
Thanks for the comment. I will implement the discriminant for now, then in the future if I need to handle default values I will open another PR.

**Comment by kbartush** [comment]
I've merged this in and released it.

https://github.com/kochavalabs/xdr-rs-serialize/tree/v0.2.1
